# Generated by Django 5.0.2 on 2024-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_applications_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='slug',
        ),
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
