# Generated by Django 5.0.2 on 2024-02-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='id_by_vacancy',
            new_name='custom_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='id_by_applicant',
        ),
    ]
