# Generated by Django 5.0.2 on 2024-02-24 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('completion_deadline', models.DateField()),
                ('status', models.CharField(choices=[('AC', 'АКТИВНЫЙ'), ('CO', 'ЗАВЕРШЕН'), ('VA', 'ЕСТЬ ВАКАНСИИ')], default='VA', max_length=2)),
                ('checkpoints_num', models.IntegerField(default=1)),
                ('participants_num', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='projects', to='account.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('custom_id', models.IntegerField(null=True)),
                ('applications_num', models.IntegerField(default=1)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('custom_id', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='projects.project')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
    ]
