# Generated by Django 5.0.2 on 2024-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='checkpoints_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants_num',
            field=models.IntegerField(default=0),
        ),
    ]
