version: '3.10'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/studentProjects/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=studproj
      - POSTGRES_PASSWORD=studpass
      - POSTGRES_DB=studproj
volumes:
  postgres_data: